# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c68e1fb81a3a6a7be1e9d3303e99b0c7bc2500807754229900a74bfaa75a2680d09f2d97370df9132afea0647a0c72b394dc432c6366c9e56575e3b5fe4ee159

test:
  secret_key_base: 695e13e9113180ddc87b1336c61b8fd992f97ae5240d706f5796adc9844fa606255cd81fa4b38b2282f7f76a1d6c453c24aec45b59e3c261d094a97d8b814060

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
